### ISSUE TITLE
On each run using IBM provider metadata has different JSON structure

### ISSUE THREAD

**Issue by akocbek** [IBM-Cloud/terraform-config-inspect#12]
Generating module metadata using `terraform-provider-ibm/metadata/provider_metadata.json` provider builds JSON object with unsorted array of strings. Therefore every time when we generate a metadata the object has different structure (see picture) 

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/106765658/191502799-b55ec283-654d-4222-b1ef-9b088d197e97.png">

For that reason our pre-commit hook fails because the json file has been changed.  

We propose to alphabetically sort array of strings.

**Comment by kavya498** [comment]
@akocbek , can you please share us the command that you used to run?

**Comment by akocbek** [comment]
@kavya498 `terraform-config-inspect --json > module-metadata.json --metadata terraform-provider-ibm/metadata/provider_metadata.json` against https://github.ibm.com/GoldenEye/vpc-module

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-config-inspect/pull/14
