### ISSUE TITLE
Running a tool with a ibm terraform provider results with inconsistent data

### ISSUE THREAD

**Issue by akocbek** [IBM-Cloud/terraform-config-inspect#13]
We ran a metadata generator tool using terraform provider on a same unchanged terraform module multiple times. Sometimes the values of created JSON file are different from previous run.

See the following code changes the generator created

**First run**
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/106765658/191678453-ee5961b1-80a8-48a0-b39c-d2cfe8a7aa44.png">

Source of `ibm_region` has been changed from `"module.vpc_subnets.ibm_is_vpc_address_prefix.subnet_prefix.zone",` to `"module.vpc_subnets.ibm_is_subnet.subnet.zone",`

**Second run**
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/106765658/191678666-c2a8cce1-574b-4bf8-919d-7a31c0358b3f.png">

 Source of `ibm_region` has been changed from `"module.vpc_subnets.ibm_is_subnet.subnet.zone",` to `"module.vpc_subnets.ibm_is_vpc_address_prefix.subnet_prefix.zone",`

Terraform provider we used: `.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.45.1/darwin_amd64/provider_metadata.json`
Repo we used: https://github.ibm.com/GoldenEye/vpc-module

We would expect that if terraform module code is not changed we would always have the same JSON data. If we do not use terraform provider then we do not have that issue.

**Comment by kavya498** [comment]
@akocbek,
Can you please use `--filter-variables` in the command
We have excluded source and pos in that json..

**Comment by akocbek** [comment]
using `--filter-variables` I do not see error mentioned above because `source` and `pos` are removed from JSON object.

now I am seeing issue with  `unique_name`. 

**first run** 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/106765658/191724969-bdca4c87-7d20-4495-962f-13d2745999a1.png">

**second run**

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/106765658/191724679-27cb7c68-b8a8-4dee-92f8-9c4e5c57fdb8.png">

**Comment by akocbek** [comment]
here I ran `pre-commit` multiple times and we can see that first hook failed (changed metadata JSON), then passed couple of times and then failed again changing back to previous metadata JSON

```
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Failed
- hook id: terraform-config-inspect
- files were modified by this hook

2022/09/22 11:31:19 Loading module 'zone_subnet_addrs' from the path './.terraform/modules/zone_subnet_addrs'
2022/09/22 11:31:19 Loading module 'vpc_subnets' from the path '././subnet'
2022/09/22 11:31:19 Loading module 'client_to_site_vpn' from the path './.terraform/modules/client_to_site_vpn'

MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Passed
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Passed
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Passed
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Passed
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Passed
MacBook-Pro:vpc-module akocbek$ pre-commit run --all-files
Generate terraform module metadata PY....................................Failed
- hook id: terraform-config-inspect
- files were modified by this hook
```

**Comment by akocbek** [comment]
@kavya498 ^

**Comment by kavya498** [comment]
@akocbek, I ll take a look at it and get back to you on this..

**Comment by akocbek** [comment]
@kavya498 did you manage to make any progress on it?

**Comment by kavya498** [comment]
We are working on it..
We ll fix and release by end of next week..

**Comment by kavya498** [comment]
https://github.com/IBM-Cloud/terraform-config-inspect/pull/16
